1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array

2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.

3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [ ]:
# import necessary library
import numpy as np

In [3]:
# 1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

range_array = np.random.randint(1,50, size=(6, 6))
print(range_array)


[[27 22 38 31 21 28]
 [ 8 24  8  7 46  3]
 [17 18  8 49 30 31]
 [47 14 40 29 36 17]
 [27 33 15 26 44 48]
 [43  5 19 34 12 33]]


In [4]:
# 2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.


# print first two rows
rows = np.array([0, 1])
print("The first two rows are:\n", range_array[rows])

# print last three columns
column1 = range_array[:, -3]
column2 = range_array[:, -2]
column3 = range_array[:, -1]
print("\nThe last three columns are:\n", column1, "\n", column2, "\n", column3)

# print all even numbers in the array
even_numbers = range_array[range_array % 2 == 0]
print("\n The even numbers in the array are:\n", even_numbers)


The first two rows are:
 [[27 22 38 31 21 28]
 [ 8 24  8  7 46  3]]

The last three columns are:
 [31  7 49 29 26 34] 
 [21 46 30 36 44 12] 
 [28  3 31 17 48 33]

 The even numbers in the array are:
 [22 38 28  8 24  8 46 18  8 30 14 40 36 26 44 48 34 12]


In [5]:
# 3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

# Reshape the (3,2,6) into a 3D array
transformed3d = range_array.reshape(3, 2,6)
print("The reshaped form of the array into 3D is:\n", transformed3d)

flattened = transformed3d.flatten()

The reshaped form of the array into 3D is:
 [[[27 22 38 31 21 28]
  [ 8 24  8  7 46  3]]

 [[17 18  8 49 30 31]
  [47 14 40 29 36 17]]

 [[27 33 15 26 44 48]
  [43  5 19 34 12 33]]]


In [ ]:
# 4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

identity = np.eye(4)
print("This is the 4 x 4 identity matrix:\n", identity)                                                # create a scalar with with the diagonal numbers will be multiplied

numbers = identity*np.diag(np.arange(10, 50, 10))
print("\nThis is the identity matrix whose diagonal numbers have been replaced:\n", numbers)


# Another method
# identity_matrix = np.eye(4)     # create the identity matrix 
# number = np.arange(10, 41, 10)        #create a variable to save the diagonal numbers with a step of 10
# np.fill_diagonal(identity_matrix, number)      # fill the identity matrix with the new diagonal numbers 



array([[10.,  0.,  0.,  0.],
       [ 0., 20.,  0.,  0.],
       [ 0.,  0., 30.,  0.],
       [ 0.,  0.,  0., 40.]])

In [ ]:
# 5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10) 
# create the matrices
matrix_A = np.random.randint(1, 11, size=(3, 4))
matrix_B = np.random.randint(1, 11, size=(3, 4)) 
print('Matrix A is \n', matrix_A)
print("\nMatrix B is \n", matrix_B)

# reshape one of the arrays to allow for multiplication
matrixB_reshaped = matrix_B.reshape(4, 3)
print("\nReshaped array:\n", matrix_B)


# Multiply both arrays
multiplied = matrix_A *  matrixB_reshaped 
print("\nThe result of the matrix multiplication is:\n", multiplied)


Matrix A is 
 [[7 3 7 7]
 [1 8 8 9]
 [7 9 7 8]]

Matrix B is 
 [[7 6 2]
 [7 4 7]
 [9 5 1]
 [7 7 2]]

The result of the matrix multiplication is:
 [[182 138  56]
 [198 141  84]
 [231 169 100]]


In [ ]:
# 6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

import numpy as np

def numpy_array(input_numpy):
    # Make a copy
    array_copy = input_numpy.copy()

    # Square even numbers
    array_copy[array_copy % 2 == 0] = array_copy[array_copy % 2 == 0] ** 2

    # Replace odd numbers with -1
    array_copy[array_copy % 2 != 0] = -1

    return array_copy

# collect input
array_rows = int(input("Please enter the number of rows: "))
array_columns = int(input("Please enter the number of columns: "))

# range the numbers and reshape
array = np.arange(array_rows * array_columns).reshape(array_rows, array_columns)

print("\nOriginal Array:")
print(array)

print("\Calculated Array:")
print(numpy_array(array))



# ANOTHER METHOD
# def numpy_array(input_array):
#     output_array = np.where(input_array % 2 == 0, input_array**2, -1)
#     return output_array

# test_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# result = numpy_array(test_array)
# print("Input Array:\n", test_array)
# print("Output Array:\n", result)


Input Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Output Array:
 [[-1  4 -1]
 [16 -1 36]
 [-1 64 -1]]
