In [3]:
# import necessary libraries
import numpy as np


In [4]:
# 1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

range_array = np.random.randint(1,50, size=(6, 6))
print(range_array)


[[26 15 36 15 46 44]
 [39 18 41  1 26  2]
 [42 22 19  8 10 29]
 [13 13 44 18 45 48]
 [34  9 33 33 47  1]
 [35 11  3 31 13  4]]


In [5]:
# 2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.


# print first two rows
rows = np.array([0, 1])
print("The first two rows are:\n", range_array[rows])

# print last three columns
column1 = range_array[:, -3]
column2 = range_array[:, -2]
column3 = range_array[:, -1]
print("\nThe last three columns are:\n", column1, "\n", column2, "\n", column3)

# print all even numbers in the array
even_numbers = range_array[range_array % 2 == 0]
print("\n The even numbers in the array are:\n", even_numbers)


The first two rows are:
 [[26 15 36 15 46 44]
 [39 18 41  1 26  2]]

The last three columns are:
 [15  1  8 18 33 31] 
 [46 26 10 45 47 13] 
 [44  2 29 48  1  4]

 The even numbers in the array are:
 [26 36 46 44 18 26  2 42 22  8 10 44 18 48 34  4]


In [6]:
# 3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

# Reshape the (3,2,6) into a 3D array
transformed3d = range_array.reshape(3, 2,6)
print("The reshaped form of the array into 3D is:\n", transformed3d)

flattened = transformed3d.flatten()

The reshaped form of the array into 3D is:
 [[[26 15 36 15 46 44]
  [39 18 41  1 26  2]]

 [[42 22 19  8 10 29]
  [13 13 44 18 45 48]]

 [[34  9 33 33 47  1]
  [35 11  3 31 13  4]]]


In [ ]:
# Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

# create the identity matrix 
identity_matrix = np.eye(4) 
print("This is the 4 x 4 identity matrix:\n", identity_matrix)                                                # create a scalar with with the diagonal numbers will be multiplied

#create a variable to save the diagonal numbers with a step of 10
number = np.arange(10, 41, 10)        

# fill the identity matrix with the new diagonal numbers 
np.fill_diagonal(identity_matrix, number)      




This is the 4 x 4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

This is the identity matrix whose diagonal numbers have been replaced:
 [[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


In [8]:
# 5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)
#  create two range arrays of different shapes
range_array1 = np.random.randint(1,11, size=(3, 4))
range_array2 = np.random.randint(1,11, size=(4, 3))
print("First array:\n", range_array1)
print("\nSecond array:\n", range_array2)

# reshape one of the arrays to allow for multiplication
array1_reshaped = range_array1.reshape(4, 3)
print("\nReshaped first array:\n", array1_reshaped)

# Multiply both arrays
multiplied = array1_reshaped * range_array2
print("\n First array multiplied by second array\n", multiplied)

First array:
 [[9 8 9 9]
 [7 3 4 1]
 [7 2 2 2]]

Second array:
 [[10  1  9]
 [ 3  5  7]
 [ 6  5  9]
 [10  2 10]]

Reshaped first array:
 [[9 8 9]
 [9 7 3]
 [4 1 7]
 [2 2 2]]

 First array multiplied by second array
 [[90  8 81]
 [27 35 21]
 [24  5 63]
 [20  4 20]]


In [ ]:
# 6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

# First create a function to take 2D numpy array as input
def numpy_array(input_numpy):
    # create a copy of the inpu tby flattening
    array_copy = input_numpy.flatten()
    print("The copy of the array enetered is:\n", array_copy)

    # check if there are even numbers in the array 
    even_arrays = array_copy[array_copy % 2 == 0]
    # square the even numbers
    squared_even = pow(even_arrays, 2)
    print("\n The even numbers in the array above are:\n", even_arrays)
    print("\n The square of the even numbers above are:\n", squared_even)


    # check if there are odd numbers in the array
    odd_arrays = array_copy[array_copy % 2 != 0]
    # replace odd numbers with -1
    replaced_odd = array_copy[odd_arrays, -1]
    print("The odd numbers in the array above are:\n", odd_arrays)
    print("The odd numbers have now been replaced with -1:\n", replaced_odd)




In [ ]:
import numpy as np

def numpy_array(input_numpy):
    # Make a copy
    array_copy = input_numpy.copy()

    # Square even numbers
    array_copy[array_copy % 2 == 0] = array_copy[array_copy % 2 == 0] ** 2

    # Replace odd numbers with -1
    array_copy[array_copy % 2 != 0] = -1

    return array_copy

# collect input
array_rows = int(input("Please enter the number of rows: "))
array_columns = int(input("Please enter the number of columns: "))

# range the numbers and reshape
array = np.arange(array_rows * array_columns).reshape(array_rows, array_columns)

print("\nOriginal Array:")
print(array)

print("\Calculated Array:")
print(numpy_array(array))

# Another solution

# def numpy_array(input_array):
#     output_array = np.where(input_array % 2 == 0, input_array**2, -1)
#     return output_array

# test_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# result = numpy_array(test_array)
# print("Input Array:\n", test_array)
# print("Output Array:\n", result)


<>:26: SyntaxWarning: "\C" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\C"? A raw string is also an option.
<>:26: SyntaxWarning: "\C" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\C"? A raw string is also an option.
C:\Users\Deborah Adelegan\AppData\Local\Temp\ipykernel_6680\2479309442.py:26: SyntaxWarning: "\C" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\C"? A raw string is also an option.
  print("\Calculated Array:")



Original Array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
\Calculated Array:
[[  0  -1   4]
 [ -1  16  -1]
 [ 36  -1  64]
 [ -1 100  -1]]
